FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install ChromaDB
RUN pip install chromadb

# Expose port (default for chromadb server)
EXPOSE 8000

#TODO: env var
# Start chromadb server
CMD ["chromadb", "run", "--host", "0.0.0.0", "--port", "8000", "--path", "/data"]
