version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    depends_on:
      - chromadb
      - ollama
      - mysql

  mysql:
    build:
      context: ./mysql
    container_name: mysql_db
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  chromadb:
    build:
      context: ./chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve

volumes:
  mysql_data:
  chroma_data:
  ollama_data:
