version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
    container_name: mysql_db
    hostname: mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_db_container
    ports:
      - "8000:8000"
    restart: unless-stopped

  ollama:
    build:
      context: ./ollama
    container_name: ollama_server
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL_INSTALL=${OLLAMA_MODEL_INSTALL}
    volumes:
      - ollama_data:/root/.ollama
      
  backend:
    build:
      context: ./backend
    environment:
      API_PORT: ${API_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      CHROMA_HOST: ${CHROMA_HOST}
      CHROMA_PORT: ${CHROMA_PORT}
    ports:
      - "4000:4000"
    volumes:
      - ./db:/app/db
    depends_on:
      - chromadb
      - ollama
      - mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend


volumes:
  mysql_data:
  chroma_data:
  ollama_data:
